---

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:${IMAGE_VARIANT:-latest}
    security_opt:
      - label:type:docker_t
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/tmp/docker.sock:ro
      - ${TLS_DIRECTORY_PATH:?}:/etc/nginx/certs
    ports:
      - '${HTTP_PORT:-80}:${HTTP_PORT:-80}'
      - '${HTTPS_PORT:-443}:${HTTPS_PORT:-443}'
    restart: ${RESTART_POLICY:-no}
    networks:
      - ${NETWORK_NAME:-proxy}

networks:
  edge:
    name: ${NETWORK_NAME:-proxy}
    attachable: true
